### ISSUE TITLE
Getting System.IO.IOException when trying the operation CreateFileWithinFolder

### ISSUE THREAD

**Issue by isurul28** [wso2-extensions/esb-connector-sharepoint#15]
**Description:**
We are getting the System.IO.IOException when invoking the CreateFileWithinFolder. The reason for this from EI we are not sending the header Content-Length to the backend. We are sending a Transfer-Encoding: chunked.
Need to add chunking disabling property before Post Call to sharepoint API.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Sharepoint connector
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

https://docs.wso2.com/display/ESBCONNECTORS/Working+with+folders+and+files#Workingwithfoldersandfiles-createFileWithinFolder

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3516
